AWSTemplateFormatVersion: '2010-09-09'
Description: 'WhatsApp Bot on EC2 Windows - Automated Deployment'

Parameters:
  KeyPairName:
    Type: String
    Description: EC2 Key Pair name (create one first in EC2 console)
    Default: whatsapp-bot-key
  
  MyIPAddress:
    Type: String
    Description: Your IP address for RDP access (e.g., 1.2.3.4/32)
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})

Resources:
  # S3 Bucket for contacts and logs
  WhatsAppBotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'whatsapp-bot-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Security Group for RDP access
  WhatsAppBotSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WhatsAppBotSG
      GroupDescription: Allow RDP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !Ref MyIPAddress
          Description: RDP access

  # IAM Role for EC2
  WhatsAppBotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt WhatsAppBotBucket.Arn
                  - !Sub '${WhatsAppBotBucket.Arn}/*'

  WhatsAppBotInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WhatsAppBotRole

  # EC2 Instance
  WhatsAppBotInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base}}'
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref WhatsAppBotInstanceProfile
      SecurityGroupIds:
        - !Ref WhatsAppBotSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: WhatsApp-Bot-Server
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          # Set execution policy
          Set-ExecutionPolicy Bypass -Scope Process -Force
          
          # Install Chocolatey
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          # Refresh environment
          $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
          
          # Install Python and Chrome
          choco install python googlechrome -y
          
          # Refresh PATH
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          
          # Wait for Python installation
          Start-Sleep -Seconds 30
          
          # Install Python packages
          python -m pip install --upgrade pip
          python -m pip install pandas selenium boto3
          
          # Download ChromeDriver
          $chromeVersion = (Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.ProductVersion
          $chromeDriverVersion = $chromeVersion.Substring(0, $chromeVersion.LastIndexOf('.'))
          
          # Use a stable ChromeDriver version
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip" -OutFile "C:\chromedriver.zip"
          Expand-Archive -Path "C:\chromedriver.zip" -DestinationPath "C:\Windows\System32\" -Force
          
          # Create project directory
          New-Item -ItemType Directory -Path "C:\whatsapp-bot" -Force
          
          # Download bot script from S3 (you'll upload it after stack creation)
          # aws s3 cp s3://${WhatsAppBotBucket}/bot_scheduled.py C:\whatsapp-bot\
          # aws s3 cp s3://${WhatsAppBotBucket}/contacts.csv C:\whatsapp-bot\
          
          # Create a simple test file
          @"
          import pandas as pd
          print('WhatsApp Bot Environment Ready!')
          print('Python and dependencies installed successfully.')
          "@ | Out-File -FilePath "C:\whatsapp-bot\test.py" -Encoding UTF8
          
          # Disable sleep and screen timeout
          powercfg -change -monitor-timeout-ac 0
          powercfg -change -standby-timeout-ac 0
          
          # Create setup completion marker
          "Setup completed at $(Get-Date)" | Out-File -FilePath "C:\whatsapp-bot\setup_complete.txt"
          
          </powershell>

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WhatsAppBotInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  
  InstancePublicIP:
    Description: Public IP address for RDP connection
    Value: !GetAtt WhatsAppBotInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  
  BucketName:
    Description: S3 Bucket for contacts and logs
    Value: !Ref WhatsAppBotBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  RDPConnection:
    Description: RDP connection command
    Value: !Sub 'mstsc /v:${WhatsAppBotInstance.PublicIp}'
